version: "3"
services: 
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/caches:/data-cache
    environment:
      - TZ=Asia/Bangkok
      - NGINX_PORT=80
    restart: always
    networks:
      - frontend-network
  web01:
    image: porchn/php5.6-apache:latest
    volumes:
      - ./docroot:/var/www/html
      - log:/log
    environment:
      - TZ=Asia/Bangkok
    networks:
      - frontend-network
      - backend-network
    hostname: web
    restart: always

 

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: testdb
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    restart: always
    networks:
      - backend-network
volumes:
  log:

 

networks:
  frontend-network:
  backend-network:
